// Command bcp-matches-manifest writes a newline manifest of bcp-export JSON shards for
// local-elo -matches-manifest / eloevent-discord-bot / refresh-leaderboard.sh.
//
// With no arguments, defaults to bcp-matches-*.json in the working directory.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

func main() {
	outPath := flag.String("out", "bcp-matches.manifest", "write manifest here (use - for stdout)")
	sortMode := flag.String("sort", "name", `order shards: "name" (lexical, good for YYYY-MM-DD suffixes), "mtime" (oldest first), "none" (argv/glob order)`)
	noHeader := flag.Bool("no-header", false, "omit the leading # comment lines")
	flag.Parse()

	paths, err := collectPaths(flag.Args())
	if err != nil {
		log.Fatal(err)
	}
	if len(paths) == 0 {
		fmt.Fprintln(os.Stderr, "Usage: bcp-matches-manifest [-out bcp-matches.manifest] [-sort name|mtime|none] [file-or-glob ...]")
		fmt.Fprintln(os.Stderr, "  With no args: glob bcp-matches-*.json in the current directory.")
		os.Exit(2)
	}

	for _, p := range paths {
		if st, err := os.Stat(p); err != nil || st.IsDir() {
			if err != nil {
				log.Fatalf("stat %q: %v", p, err)
			}
			log.Fatalf("not a file: %s", p)
		}
	}

	switch *sortMode {
	case "name":
		sort.Strings(paths)
	case "mtime":
		type pair struct {
			path string
			t    time.Time
		}
		var ps []pair
		for _, p := range paths {
			st, err := os.Stat(p)
			if err != nil {
				log.Fatal(err)
			}
			ps = append(ps, pair{path: p, t: st.ModTime()})
		}
		sort.Slice(ps, func(i, j int) bool { return ps[i].t.Before(ps[j].t) })
		for i := range ps {
			paths[i] = ps[i].path
		}
	case "none":
		// keep order
	default:
		log.Fatalf("-sort must be name, mtime, or none")
	}

	absOut, err := filepath.Abs(*outPath)
	if err != nil {
		log.Fatal(err)
	}
	outDir := filepath.Dir(absOut)
	if *outPath == "-" {
		outDir, _ = os.Getwd()
	}

	lines := make([]string, 0, len(paths))
	for _, p := range paths {
		absP, err := filepath.Abs(p)
		if err != nil {
			log.Fatal(err)
		}
		line := absP
		if rel, err := filepath.Rel(outDir, absP); err == nil && rel != "" && !strings.HasPrefix(rel, "..") {
			line = filepath.ToSlash(rel)
		}
		lines = append(lines, line)
	}

	var sb strings.Builder
	if !*noHeader {
		sb.WriteString("# Generated by bcp-matches-manifest; used with: local-elo -matches-manifest ")
		if *outPath == "-" {
			sb.WriteString("<this-file>\n")
		} else {
			sb.WriteString(filepath.ToSlash(*outPath))
			sb.WriteString("\n")
		}
		sb.WriteString("# Shards are merged in listed order; overlaps dedupe (first row wins).\n")
	}
	for _, ln := range lines {
		sb.WriteString(ln)
		sb.WriteString("\n")
	}

	data := []byte(sb.String())
	if *outPath == "-" {
		if _, err := os.Stdout.Write(data); err != nil {
			log.Fatal(err)
		}
		return
	}
	if err := os.WriteFile(*outPath, data, 0o644); err != nil {
		log.Fatalf("write %s: %v", *outPath, err)
	}
	fmt.Fprintf(os.Stderr, "wrote %d paths → %s\n", len(lines), *outPath)
}

func collectPaths(args []string) ([]string, error) {
	if len(args) == 0 {
		m, err := filepath.Glob("bcp-matches-*.json")
		if err != nil {
			return nil, err
		}
		args = m
	}
	seen := make(map[string]struct{})
	var out []string
	for _, arg := range args {
		matches, err := filepath.Glob(arg)
		if err != nil {
			return nil, err
		}
		if len(matches) == 0 && !strings.ContainsAny(arg, "*?[") {
			matches = []string{arg}
		}
		for _, m := range matches {
			m = filepath.Clean(m)
			if _, ok := seen[m]; ok {
				continue
			}
			seen[m] = struct{}{}
			out = append(out, m)
		}
	}
	return out, nil
}
